version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8018:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - TRUST_DOWNSTREAM_PROXY=true


  user_app:
      image: lineblocs/user-app:${VERSION}
      container_name: lineblocs-app
      environment:
        - LINEBLOCS_VERSION=${VERSION}
        - DEPLOYMENT_DOMAIN=${DEPLOYMENT_DOMAIN}
        - PORT=8010
        - VIRTUAL_HOST=app.${DEPLOYMENT_DOMAIN}
        - VIRTUAL_PORT=8010