version: "3.8"
#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  # start of voip definitions
  opensips:
    image: lineblocs/opensips-proxy:${VERSION}
    logging: *default-logging
    container_name: lineblocs-opensips
    restart: unless-stopped
    environment:
      - DB_HOST=${CONFIG_DB_HOST:-}
      - DB_USER=${CONFIG_DB_USERNAME:-}
      - DB_PASSWORD=${CONFIG_DB_PASSWORD:-}
      - DB_NAME=${CONFIG_DB_OPENSIPS_DATABASE:-}
      - DEPLOYMENT_DOMAIN=${DEPLOYMENT_DOMAIN}
      - RTPPROXY_IPV4=${DEPLOYMENT_DOMAIN}
      - LINEBLOCS_KEY=${LINEBLOCS_KEY}
      - API_URL=http://internals.${DEPLOYMENT_DOMAIN:-}
    network_mode: "host"